version: '3'

services:
  transformer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
    ports:
      - "8888:8888"  # 用于Jupyter Notebook
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: bash -c "jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='transformer'"

  train:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: python src/train.py --epochs 10 --batch_size 128 --save_dir models/

  evaluate:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./models:/app/models
      - ./results:/app/results
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: python src/evaluate.py --model_path models/transformer-model.pt --beam_sizes "1 3 5 10" --test_data Multi30k